### ISSUE TITLE
Undefined name 'scanner'.

### ISSUE THREAD

**Issue by JordanDalton** [ivirtex/lan_scanner#3]
```
final stream = scanner.icmpScan('192.168.0', progressCallback: (progress) {
    print('Progress: $progress');
});

stream.listen((HostModel device) {
    print("Found host: ${device.ip}");
});
```

    lib/main.dart:146:18: Error: Undefined name 'scanner'.
      final stream = scanner.icmpScan('192.168.0', progressCallback: (progress) {
                     ^^^^^^^
    Failed to package /Users/jordandalton/StudioProjects/goldshell.
    Command PhaseScriptExecution failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by ivirtex** [comment]
Hi!

It seems that you forgot to create an instance of LanScanner:
`final scanner = LanScanner()`

I will update the documentation in the next version.

But I am worried that you may still encounter some issues while running the app on an iOS device. There is a bug related to the main dependency not allowing to use of the library on iOS, other platforms should be unaffected.
I will address this bug in the next version.

**Comment by JordanDalton** [comment]
Yeah, it's not playing nicely with iOS. Could we get the LanScanner() instance added to the readme?

**Comment by ivirtex** [comment]
Sorry for delayed response, I updated the readme some time ago.

Thank you for opening this issue, let me know if you have any other questions.
