### ISSUE TITLE
Missing permission in AndroidManifest.xml (release)

### ISSUE THREAD

**Issue by DamnDaniel-98** [ivirtex/lan_scanner#4]
After adding the package to my project, it works fine except when trying to run it as a release version. The reason is the missing permission in the AndroidManifest.xml in the release folder, which took me a long time to figure out. Maybe there is a way to add the permission automatically so that future users of the library don't have to figure it out?

**Comment by ivirtex** [comment]
Hi, thanks for using lan_scanner.

Which permission did you have to add to the `AndroidManifest.xml`?
How did you know that it wasn't working in the release mode? The stream didn't send any discovered hosts?

Thank you.

**Comment by DamnDaniel-98** [comment]
Hey, thanks for offering lan_scanner :)
The permission i had to add was  android.permission.INTERNET.
I used an await for-loop for the stream and the code stucked at this point.

**Comment by ivirtex** [comment]
Unfortunately, it is not possible to add permissions automatically, but I will address adding `android.permission.INTERNET` to the `AndroidManifest.xml` in the readme.

Thanks for spotting this bug and opening an issue, I will close it when the new version is released :)

**Comment by ivirtex** [comment]
New version is on the [pub.dev](https://pub.dev/packages/lan_scanner), I mentioned your issue in the changelog :)
