### ISSUE TITLE
Link to repo is missing in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [ivirtex/lan_scanner#5]
`Repository (GitHub)` button exist in the right side:

![image](https://user-images.githubusercontent.com/9304740/179728565-9ff401bb-3e0f-4489-9afd-6162c83e637a.png)

`Repository (GitHub)` button is missing in the right side:

![image](https://user-images.githubusercontent.com/9304740/179764996-f4c1a0e7-885c-4309-8ae5-f7b83fba9ea2.png)

I saw that the `Homepage` button is linked to this repo but that functionality is more suited for `Repository (GitHub)` button.

**Comment by ivirtex** [comment]
It seems that pub.dev now does this automatically, thanks.
