### ISSUE TITLE
Device Name 

### ISSUE THREAD

**Issue by Ddhruv-IOT** [ivirtex/lan_scanner#9]
How to get the device name too ??

**Comment by kevinconcourse** [comment]
Looking for the answer as well.

**Comment by guyluz11** [comment]
Maybe is supported on [network_tools](https://pub.dev/packages/network_tools), you can check it out

**Comment by ivirtex** [comment]
Sorry guys, I didn't see your comments before.
I don't have enough time recently to continue developing this package, so check out network_tools as mentioned in comment above if you want additional capabilities.

**Comment by Ddhruv-IOT** [comment]
Thank you everyone for support 👍 I am closing this issue as I have got the answer.
